import org.apache.commons.io.FilenameUtils

plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Framework
    implementation "com.mrcrayfish:framework-fabric:${framework_version}+${minecraft_version}"

    // JEI
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"

    // ModMenu
    compileOnly "com.terraformersmc:modmenu:${modmenu_version}"

    // Night Config
    compileOnly "com.electronwill.night-config:core:${night_config_version}"
    compileOnly "com.electronwill.night-config:toml:${night_config_version}"
}

fabricApi {
    configureDataGeneration {
        outputDirectory.set(file("src/generated"))
    }
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
            setSource(sourceSets.testmod)
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
            setSource(sourceSets.testmod)
        }
    }
}

// We don't have any tests so task should be skipped
tasks.test.enabled = false

sourceSets.main.resources.srcDir 'src/generated/resources'

tasks.register("signJar") {
    dependsOn jar
    onlyIf {
        findProperty('keyStore') || System.getenv("KEYSTORE")
    }
    doLast {
        def unsignedJar = jar.archiveFile.get().asFile
        def name = FilenameUtils.removeExtension(unsignedJar.getName())
        def signedJar  = layout.buildDirectory.file("libs/%s-signed.jar".formatted(name)).get().asFile
        def signingKeyAlias = findProperty('keyStoreAlias') ?: System.getenv("KEYSTORE_ALIAS")
        def signingKeystore = findProperty('keyStore') ?: System.getenv("KEYSTORE")
        def signingPassword = findProperty('keyStorePass') ?: System.getenv("KEYSTORE_PASS")
        ant.signjar(
            jar: unsignedJar,
            signedJar: signedJar,
            alias: signingKeyAlias,
            keyStore: signingKeystore,
            storePass: signingPassword,
            storetype: 'jks'
        )
        println "Signed jar created at: $signedJar"
    }
}
build.finalizedBy(signJar)

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}