import org.apache.commons.io.FilenameUtils

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

sourceSets {
    configuredTest {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        compileClasspath += test.compileClasspath
        runtimeClasspath += test.runtimeClasspath
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Framework
    modImplementation "com.mrcrayfish:framework-fabric:${minecraft_version}-${framework_version}"

    // JEI
    // TODO revert back to minecraft property once jei has updated
    modCompileOnly "mezz.jei:jei-1.21.10-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-1.21.10-fabric-api:${jei_version}"
    //modRuntimeOnly "mezz.jei:jei-1.21.5-fabric:${jei_version}"

    // ModMenu
    modApi "com.terraformersmc:modmenu:${modmenu_version}"

    // Night Config
    compileOnly "com.electronwill.night-config:core:${night_config_version}"
    compileOnly "com.electronwill.night-config:toml:${night_config_version}"
}

fabricApi {
    configureDataGeneration {
        outputDirectory.set(file("src/generated"))
    }
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
            setSource(sourceSets.configuredTest)
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
            setSource(sourceSets.configuredTest)
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

tasks.register("signJar") {
    dependsOn remapJar
    onlyIf {
        findProperty('keyStore') || System.getenv("KEYSTORE")
    }
    doLast {
        def unsignedJar = remapJar.archiveFile.get().asFile
        def name = FilenameUtils.removeExtension(unsignedJar.getName())
        def signedJar  = layout.buildDirectory.file("libs/%s-signed.jar".formatted(name)).get().asFile
        def signingKeyAlias = findProperty('keyStoreAlias') ?: System.getenv("KEYSTORE_ALIAS")
        def signingKeystore = findProperty('keyStore') ?: System.getenv("KEYSTORE")
        def signingPassword = findProperty('keyStorePass') ?: System.getenv("KEYSTORE_PASS")
        ant.signjar(
            jar: unsignedJar,
            signedJar: signedJar,
            alias: signingKeyAlias,
            keyStore: signingKeystore,
            storePass: signingPassword,
            storetype: 'jks'
        )
        println "Signed jar created at: $signedJar"
    }
}
build.finalizedBy(signJar)

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
loom.remapConfigurations.configureEach {
    configurations.named(it.name) {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}