package com.mrcrayfish.configured;

import net.minecraftforge.common.ForgeConfigSpec;
import org.apache.commons.lang3.tuple.Pair;

/**
 * Author: MrCrayfish
 */
public class Config
{
    public static class Client
    {
        public final ForgeConfigSpec.BooleanValue forceConfiguredMenu;

        public Client(ForgeConfigSpec.Builder builder)
        {
            this.forceConfiguredMenu = builder.comment("Forces all config menus to be overridden and generated by Configured. This requires the game to be restarted for the changes to apply.").translation("configured.config.client.force_configured_menu").define("forceConfiguredMenu", false);
        }
    }

    static final ForgeConfigSpec clientSpec;
    public static final Client CLIENT;

    static
    {
        final Pair<Client, ForgeConfigSpec> clientSpecPair = new ForgeConfigSpec.Builder().configure(Client::new);
        clientSpec = clientSpecPair.getRight();
        CLIENT = clientSpecPair.getLeft();
    }
}
