plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.5"
    compileOnly "com.mrcrayfish:framework-common:${minecraft_version}-${framework_version}"
    compileOnly "mezz.jei:jei-1.21.9-common-api:${jei_version}"
    compileOnly "com.electronwill.night-config:core:3.7.1"
    compileOnly "com.electronwill.night-config:toml:3.7.1"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}