import org.apache.commons.io.FilenameUtils

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

sourceSets {
    testmod
}

neoForge {
    enable {
        version = neoforge_version
        disableRecompilation = System.getenv("CI") == "true"
    }

    addModdingDependenciesTo sourceSets.testmod

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    mods {
        catalogue {
            sourceSet sourceSets.main
        }
        testmod {
            sourceSet sourceSets.testmod
        }
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    implementation "com.mrcrayfish:framework-neoforge:${framework_version}+${minecraft_version}"
    testmodImplementation "com.mrcrayfish:framework-neoforge:${framework_version}+${minecraft_version}"

    // JEI
    //compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    //testCompileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    //runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
}

tasks.register("signJar") {
    dependsOn jar
    onlyIf {
        findProperty('keyStore') || System.getenv("KEYSTORE")
    }
    doLast {
        def unsignedJar = tasks.jar.archiveFile.get().asFile
        def name = FilenameUtils.removeExtension(unsignedJar.getName())
        def signedJar  = layout.buildDirectory.file("libs/%s-signed.jar".formatted(name)).get().asFile
        def signingKeyAlias = findProperty('keyStoreAlias') ?: System.getenv("KEYSTORE_ALIAS")
        def signingKeystore = findProperty('keyStore') ?: System.getenv("KEYSTORE")
        def signingPassword = findProperty('keyStorePass') ?: System.getenv("KEYSTORE_PASS")
        ant.signjar(
            jar: unsignedJar,
            signedJar: signedJar,
            alias: signingKeyAlias,
            keyStore: signingKeystore,
            storePass: signingPassword,
            storetype: 'jks'
        )
        println "Signed jar created at: $signedJar"
    }
}

jar.finalizedBy 'signJar'

// Disables JUnit on test packages on build
tasks.configureEach { task ->
    if (task.name.startsWith("testJunit")) {
        task.enabled = false
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
